import type { Metadata } from "next";
import localfont from 'next/font/local'
import "./globals.css";


const abibas = localfont({
  src: [
    {
      path: '../public/fonts/Abibas.ttf',
      weight: '700'
    }
  ],
  variable: '--font-abibas'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${abibas.variable} bg-black`}>
    <body className="">
      
      <main className="relative overflow-hidden font-abibas ">
      {children}
      </main>
      
    </body>
  </html>
  );
}
